# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go

matrix:
 include:
  - go: 1.4.3
    install:
     - go get golang.org/x/tools/cmd/cover
     - go get golang.org/x/tools/cmd/vet
  - go: 1.5.2

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools
 - sudo apt-get install -y build-essential

script:
 - ./autogen.sh
 - ./configure --with-stage1-default-name="example.com/some-stage1-for-rkt" --with-stage1-default-version="0.0.1"
 - make unit-check
